### ISSUE TITLE
Control Missing From Toolbox

### ISSUE THREAD

**Issue by ghost** [sontx/simple-datagridview-paging#1]
Hi - The paging control doesn't appear in the Visual Studio (2013) toolbox after it's installed.  I don't know how to make it appear.  Suggestions?

**Comment by sontx** [comment]
Hi @BillBoroson, you can add simple-datagridview-paging to your toolbox by right click to toolbox and then "Choose items...", in .NET Framework Components tab, click to "Browse..." button and select SimpleDataGridViewPaging.dll file(in Debug/Release folder if you built your project before). Finally, click on Open button and OK, it will appear in your toolbox :)
