### ISSUE TITLE
Need to change 

### ISSUE THREAD

**Issue by Igor-san** [sontx/simple-datagridview-paging#4]
https://github.com/sontx/simple-datagridview-paging/blob/1f03c10e8ba78ec8136e620d5bcc05dcbe68f278/SimpleDataGridViewPaging/DataGridViewPaging.EventHandling.cs#L55

need to change 
to
**if (pageNumber >= 1 && pageNumber <= totalPages)**

**Comment by sontx** [comment]
Fixed, thank you very much.
